### ISSUE TITLE
Group history

### ISSUE THREAD

**Issue by fleaz** [OpenSplit/opensplit-backend#13]
Especially when we allow users to delete expenses via the frontend or when they start to use the new 'Payment' feature it would be necessary to have some kind of history inside a group.
This would include:
  * Someone joined the grouped
  * Someone left the group
  * Expense added
  * Expense deleted
  * Payment added
  * Payment deleted (Is this even possible?)

For the events a simple table with {id, timestamp, eventtype, description} would be enough I guess.

Otherwise it would imho not be possible to follow the actions inside a group and the user wont understand what is happening and how their debts are created.

Opinions on this?

**Comment by mweinelt** [comment]
Maybe also reference the eventid that can be used to reference to some transaction or user.
